//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talegen.AspNetCore.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Talegen.AspNetCore.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talegen App.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multipart boundary length limit {0} exceeded..
        /// </summary>
        internal static string ErrorContentTypeBoundaryLimitExceededText {
            get {
                return ResourceManager.GetString("ErrorContentTypeBoundaryLimitExceededText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing content-type boundary..
        /// </summary>
        internal static string ErrorContentTypeBoundryNotFoundText {
            get {
                return ResourceManager.GetString("ErrorContentTypeBoundryNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message template folder &apos;{0}&apos; was not found. Message template system cannot work without template files..
        /// </summary>
        internal static string ErrorEmailTemplateDirectoryNotFoundText {
            get {
                return ResourceManager.GetString("ErrorEmailTemplateDirectoryNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        internal static string ErrorGeneralWebText {
            get {
                return ResourceManager.GetString("ErrorGeneralWebText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalidate message type &apos;{0}&apos; was found in queue and could not be converted to object..
        /// </summary>
        internal static string ErrorInvalidMessageTypeText {
            get {
                return ResourceManager.GetString("ErrorInvalidMessageTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing a message in message queue..
        /// </summary>
        internal static string ErrorMessageSenderText {
            get {
                return ResourceManager.GetString("ErrorMessageSenderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application configuration class &apos;{0}&apos; was not found in the configuration..
        /// </summary>
        internal static string ErrorNoConfigurationText {
            get {
                return ResourceManager.GetString("ErrorNoConfigurationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A query object could not be created in &apos;{0}&apos; causing failure..
        /// </summary>
        internal static string ErrorNoQueryText {
            get {
                return ResourceManager.GetString("ErrorNoQueryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No repository results were found in &apos;{0}&apos; call causing &apos;{1}&apos; failure..
        /// </summary>
        internal static string ErrorNoRepositoryResultFoundText {
            get {
                return ResourceManager.GetString("ErrorNoRepositoryResultFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load queued messages from folder &apos;{0}&apos; because &apos;{1}&apos;..
        /// </summary>
        internal static string ErrorRestoreMessageQueueText {
            get {
                return ResourceManager.GetString("ErrorRestoreMessageQueueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the SMTP processor execution..
        /// </summary>
        internal static string ErrorSmtpSenderExceptionText {
            get {
                return ResourceManager.GetString("ErrorSmtpSenderExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} message must be of type {1}..
        /// </summary>
        internal static string ErrorSmtpSenderInvalidTypeText {
            get {
                return ResourceManager.GetString("ErrorSmtpSenderInvalidTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to store queued messages to folder &apos;{0}&apos; because &apos;{1}&apos;..
        /// </summary>
        internal static string ErrorStoreMessageQueueText {
            get {
                return ResourceManager.GetString("ErrorStoreMessageQueueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host is exiting due to error..
        /// </summary>
        internal static string HostTerminatedErrorText {
            get {
                return ResourceManager.GetString("HostTerminatedErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed Hosted Message Queue Job is running..
        /// </summary>
        internal static string MessageQueueJobStartText {
            get {
                return ResourceManager.GetString("MessageQueueJobStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed Hosted Message Queue Job is stopping..
        /// </summary>
        internal static string MessageQueueJobStopText {
            get {
                return ResourceManager.GetString("MessageQueueJobStopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Background Messaging Service. Type: {0}.
        /// </summary>
        internal static string MessagingServiceProcessQueueText {
            get {
                return ResourceManager.GetString("MessagingServiceProcessQueueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring Background Messaging Service Queue. Type: {0}.
        /// </summary>
        internal static string MessagingServiceRestoreQueueText {
            get {
                return ResourceManager.GetString("MessagingServiceRestoreQueueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storing Background Messaging Service Queue. Type: {0}.
        /// </summary>
        internal static string MessagingServiceStoreQueueText {
            get {
                return ResourceManager.GetString("MessagingServiceStoreQueueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to start background worker jobs..
        /// </summary>
        internal static string StartupBackgroundWorkerErrorText {
            get {
                return ResourceManager.GetString("StartupBackgroundWorkerErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        internal static string StartupMessageText {
            get {
                return ResourceManager.GetString("StartupMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A template file name is required..
        /// </summary>
        internal static string TemplateFileNameRequired {
            get {
                return ResourceManager.GetString("TemplateFileNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A template folder path is required..
        /// </summary>
        internal static string TemplateFolderPathRequired {
            get {
                return ResourceManager.GetString("TemplateFolderPathRequired", resourceCulture);
            }
        }
    }
}
